name: omdk_sample_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:

  animations: ^2.0.11

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  hydrated_bloc: ^10.0.0

  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  flutter_flavor: ^3.1.4
  route_observer_mixin: ^1.7.0
  photo_view: ^0.15.0
  keyboard_actions: ^4.2.0
  smooth_page_indicator: ^1.2.0+3
  multi_dropdown: ^3.0.1
  timelines_plus: ^1.0.6

  modal_bottom_sheet: ^3.0.0
  intl: any
  isar: any
  omdk_repo:
    git:
      url: https://github.com/Remorides/omdk-repo.git
      ref: main

  #OPERA
  omdk_opera_api:
    git:
      url: https://github.com/Remorides/omdk-opera-api.git
      ref: dev/userGetItemsSync

  omdk_opera_repo:
    git:
      url: https://github.com/Remorides/omdk-opera-repo.git
      ref: dev_prova

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  very_good_analysis: ^7.0.0

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/company/
    - assets/icons/
    - assets/flags/
    - assets/animations/